version: "3.9"

services:
  backend:
    build: .
    container_name: yo_backend
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}" # map le port d√©fini dans le .env
    restart: unless-stopped
